version: '3.2'
services:
  mysql:
    image: mysql:5.7
    container_name: 'mysql'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=pd_db
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=app_password
    volumes:
      - ./data/:/var/lib/mysql/
    networks:
      - backend
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'phpmyadmin'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8081:80'
    networks:
      - backend
networks:
  backend:
